all:	magic_item.o item.o food_item.o lab_12_unit_test.o
	g++ -Wall -g -o lab12 item.o magic_item.o  food_item.o lab_12_unit_test.o

magc_item:	magic_item.cpp
	g++ -Wall -g -c magic_item.cpp 
	
food_item:	food_item.cpp
	g++ -Wall -g -c food_item.cpp 
	
item:	item.cpp
	g++ -Wall -g -c item.cpp 
	
lab10test:	lab_12_unit_test.cpp 
	g++ -Wall -g -c lab_12_unit_test.cpp 
