all3:	Prize.o Box.o  assign_3_unit_test.o
	g++ -Wall -g -o assign3test Prize.o Box.o assign_3_unit_test.o

assignment3:	Prize.cpp Box.cpp assign_3_unit_test.cpp
	g++ -Wall -g -c Prize.cpp Box.cpp main.cpp
	




