all:	temperature.o lab_10_unit_test.o
	g++ -Wall -g -o lab10 temperature.o lab_10_unit_test.o


temp:	temperature.cpp
	g++ -Wall -g -c temperature.cpp 
	
lab10test:	lab_10_unit_test.cpp 
	g++ -Wall -g -c lab_10_unit_test.cpp 
