all:	bst_node.o lab_24_unit_test.o bs_tree.o
	g++ -Wall -g -o lab24 bs_tree.o bst_node.o lab_24_unit_test.o


	
lab18list: bst_node.cpp bs_tree.cpp
	g++ -Wall -g -c bst_node.cpp bs_tree.cpp
	

	
labtest:	lab_24_unit_test.cpp 
	g++ -Wall -g -c lab_24_unit_test.cpp 
