all:	money.o lab_11_unit_test.o
	g++ -Wall -g -o lab11 money.o lab_11_unit_test.o


temp:	money.cpp
	g++ -Wall -g -c temperature.cpp 
	
lab10test:	lab_11_unit_test.cpp 
	g++ -Wall -g -c lab_11_unit_test.cpp 
