allOfIt:	lab_22_unit_test.o lab_22.o
	g++ -Wall -g -o Lab22 lab_22.o lab_22_unit_test.o
	
lab22unittest:	lab_22_unit_test.cpp
	g++ -Wall -g -c lab_22_unit_test.cpp
	
Lab22:	lab_22.cpp
	g++ -Wall -g -c lab_22.cpp
	