all:	sl_node.o sl_list.o lab_18_unit_test.o
	g++ -Wall -g -o lab16  sl_node.o sl_list.o lab_18_unit_test.o

lab18:	sl_node.cpp
	g++ -Wall -g -c sl_node.cpp
	
lab18list: sl_list.cpp
	g++ -Wall -g -c sl_list
	

	
labtest:	lab_18_unit_test.cpp 
	g++ -Wall -g -c lab_18_unit_test.cpp 
