lab3test: assignment_5_unit_test.o 
	g++ -Wall -g -o assignment5 assignment_5_unit_test.o 

Unit_test: assignment_5_unit_test.cpp
	g++ -Wall -g -c assignment_5_unit_test.cpp



clean:
	rm *.o assignment5
	