all:	sl_node.o lab_17_unit_test.o
	g++ -Wall -g -o lab15  sl_node.o lab_17_unit_test.o

lab14:	sl_node.cpp
	g++ -Wall -g -c sl_node.cpp 
	

	
lab14test:	lab_17_unit_test.cpp 
	g++ -Wall -g -c lab_17_unit_test.cpp 
