all:	lab_27.o lab_27_unit_test.o
	g++ -Wall -g -o lab27 lab_27.o lab_27_unit_test.o

lab18:	lab_27.cpp
	g++ -Wall -g -c sorting.cpp
	

	

	
labtest:	lab_27_unit_test.cpp 
	g++ -Wall -g -c lab_15_unit_test.cpp 
