all:	sorting.o lab_15_unit_test.o
	g++ -Wall -g -o lab15 sorting.o lab_15_unit_test.o

lab18:	sorting.cpp
	g++ -Wall -g -c sorting.cpp
	

	

	
labtest:	lab_15_unit_test.cpp 
	g++ -Wall -g -c lab_15_unit_test.cpp 
