all:	Assignment_2.o atmFunction.o
	g++ -Wall -g -o assignment2 Assignment_2.o atmFunction.o
	
	
atmFunction: atmFunction.cpp
	g++ -Wall -g -c atmFunction.cpp
	
assignment2:	Assignment_2.cpp
	g++ -Wall -g -c Assignment_2.cpp 


