all:	bst_node.o lab_23_unit_test.o
	g++ -Wall -g -o lab23  bst_node.o lab_23_unit_test.o


	
lab18list: bst_node.cpp
	g++ -Wall -g -c sl_list
	

	
labtest:	lab_23_unit_test.cpp 
	g++ -Wall -g -c lab_23_unit_test.cpp 
