all:	dl_list.o dl_node.o main.o
	g++ -Wall -g -o assignment4 dl_list.o  dl_node.o main.o
	
	
atmFunction: dl_list.cpp
	g++ -Wall -g -c dl_list.cpp
	
assignment2:	dl_node.cpp
	g++ -Wall -g -c dl_node.cpp 

main:	main.cpp
	g++ -Wall -g -c main.cpp

